using UnityEngine;

public class Player2 : MonoBehaviour
{
    public float lifetime = 5f; // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚Å‚Ìï¿½ï¿½Ôiï¿½bï¿½j
    public Collider2D Player;
    [SerializeField] private SpriteRenderer spriteRenderer;
    [Header("ï¿½_ï¿½Åİ’ï¿½")]
    public float blinkSpeed = 2f;       // ï¿½_ï¿½Å‚Ì‘ï¿½ï¿½x
    public float minAlpha = 0f;         // ï¿½Åï¿½ï¿½ï¿½ï¿½ï¿½ï¿½x
    public float maxAlpha = 1f;         // ï¿½Å‘å“§ï¿½ï¿½ï¿½x
    public float blinkStartTime = 2f;
    private Rigidbody2D rb;

    private Coroutine blinkCoroutine;
    private Color originalColor;
    public static Player2 instance;

    void Start()
    {
        instance = this;
        if (spriteRenderer == null)
            spriteRenderer = GetComponent<SpriteRenderer>();
        originalColor = spriteRenderer.color;
        rb = GetComponent<Rigidbody2D>();
        Collider2D myCollider = rb.GetComponent<Collider2D>();
        Physics2D.IgnoreCollision(myCollider,Player,true);
        // ï¿½wï¿½èï¿½ÔŒï¿½É‚ï¿½ï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½íœï¿½ï¿½ï¿½ï¿½
        Destroy(gameObject, lifetime);
        // Playerï¿½ï¿½Colliderï¿½æ“¾
        GameObject player = GameObject.FindWithTag("Player");
        if (player != null)
        {
            Collider2D playerCol = player.GetComponent<Collider2D>();
            Collider2D myCol = GetComponent<Collider2D>();

            // Playerï¿½Æ‚ÌÕ“Ë‚ğ–³ï¿½
            Physics2D.IgnoreCollision(myCol, playerCol, true);
        }
    }
    void Update()
    {
        lifetime -= Time.deltaTime;
        if (lifetime <= blinkStartTime)
        {
            float alpha = Mathf.Lerp(minAlpha, maxAlpha,
                         (Mathf.Sin(Time.time * blinkSpeed) + 1f) / 2f);

            originalColor.a = alpha;
        }
        spriteRenderer.color = originalColor;
    }

    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Conveyors"))
        {
            // Freeze Position X ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            rb.constraints = RigidbodyConstraints2D.FreezeRotation;
        }
        if (collision.gameObject.CompareTag("Lift"))
        {
            if (LiftScript.instance.egofleezeX)
            {
                rb.constraints = RigidbodyConstraints2D.FreezeRotation;
            }
            //rb.constraints = RigidbodyConstraints2D.FreezeRotation;
            transform.SetParent(collision.transform);
        }
    }
    private void OnCollisionStay2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Conveyors"))
        {
            // Freeze Position X ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            rb.constraints = RigidbodyConstraints2D.FreezeRotation;
        }
        if (collision.gameObject.CompareTag("Lift"))
        {
            if (LiftScript.instance.egofleezeX)
            {
                rb.constraints = RigidbodyConstraints2D.FreezeRotation;
            }
            //rb.constraints = RigidbodyConstraints2D.FreezeRotation;
            transform.SetParent(collision.transform);
        }
    }
    private void OnCollisionExit2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Conveyors"))
        {
            // ï¿½Ä‚ï¿½ Freeze Position X ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½
            rb.constraints = RigidbodyConstraints2D.FreezePositionX | RigidbodyConstraints2D.FreezeRotation;
        }
        if (collision.gameObject.CompareTag("Lift"))
        {
            if (LiftScript.instance.egofleezeX)
            {
                rb.constraints = RigidbodyConstraints2D.FreezePositionX | RigidbodyConstraints2D.FreezeRotation;
            }
            //rb.constraints = RigidbodyConstraints2D.FreezePositionX | RigidbodyConstraints2D.FreezeRotation;
            transform.SetParent(null);
        }
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.CompareTag("Lift"))
        {
            transform.SetParent(collision.transform);
        }
    }

}
